project_id = "agdhijvukjotypbjiiwe"

[functions.get-invite]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.send-session-reminders]
verify_jwt = false

[functions.send-exam-reminders]
verify_jwt = false

[functions.send-access-code-emails]
verify_jwt = false

[functions.skoo-tts]
verify_jwt = false

[functions.skoo-coach]
verify_jwt = false
